# Configuração da Base de Dados H2 em Memória
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ativar a consola H2 no browser (opcional, acessível em http://localhost:8080/h2-console)
spring.h2.console.enabled=true

# CRÍTICO: Manda o Hibernate criar a tabela "rallies" automaticamente ao arrancar
spring.jpa.hibernate.ddl-auto=update

# Mostra as queries SQL na consola para conseguires acompanhar o que está a ser executado
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Força o Hibernate a criar as tabelas no arranque
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
